Repository ssbc/ssb-server, pull requests merged in 2019-05, with the labels that each got.

#656 Restore ssb-links and link to ssb-minimal-pub-server
  README.md
  bin.js
Labels: Waiting For Review

#664 WIP: Replace inline modules with full and separate modules
  .gitignore
  bin.js
  npm-shrinkwrap.json
  package.json
  plugins/local.js
  plugins/logging.js
  plugins/master.js
  plugins/no-auth.js
  plugins/onion.js
  plugins/plugins.js
  plugins/plugins.md
  plugins/unix-socket.js
  test/caps.js
  test/master.js
  test/plugins.js
Labels: enhancement

#666 Fix shrinkwrap file
  npm-shrinkwrap.json
Labels: bug
